num_samples: 5000
# task_name: "bimodal_gaussian"
data_0:
  name: "eight_gaussian"
  params:
    noise: 0.05
data_1:
  name: "two_moons"
  params:
    noise: 0.05
seed: 0

  # x0:
  #   mean_1: [-2.0, 0.0]
  #   mean_2: [-2.0, 5.0]
  #   sigma_1: .1
  #   sigma_2: .2
  # x1:
  #   mean_1: [2.0, 0.0]
  #   mean_2: [2.0, 5.0]
  #   sigma_1: .1
  #   sigma_2: .2
  #

flows:
  name: "conditional"
  num_steps: 200
  params:
    noise: 0.01

networks:
  hidden_dim: 64
  lr: 1e-2
  batch_size: 512
  epochs: 20000

plots:
  n_traj: 100
